# Generated by Django 4.2.27 on 2026-01-15 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1, verbose_name='Пол')),
                ('marital_status', models.CharField(choices=[('single', 'Холост/Не замужем'), ('married', 'Женат/Замужем'), ('divorced', 'Разведён(а)'), ('widowed', 'Вдовец/Вдова')], default='single', max_length=20, verbose_name='Семейное положение')),
                ('employment', models.CharField(choices=[('employed', 'Работает'), ('self_employed', 'Самозанятый'), ('unemployed', 'Безработный'), ('retired', 'Пенсионер'), ('student', 'Студент')], default='employed', max_length=20, verbose_name='Занятость')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Доход')),
                ('has_children', models.BooleanField(default=False, verbose_name='Наличие детей')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='Город проживания')),
                ('region', models.CharField(blank=True, max_length=200, verbose_name='Регион проживания')),
                ('phone_mobile', models.CharField(blank=True, max_length=32, verbose_name='Телефон (мобильный)')),
                ('phone_work', models.CharField(blank=True, max_length=32, verbose_name='Телефон (рабочий)')),
                ('phone_home', models.CharField(blank=True, max_length=32, verbose_name='Телефон (домашний)')),
                ('monthly_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ежемесячные расходы')),
                ('category', models.CharField(choices=[('standard', 'Стандартный'), ('vip', 'VIP'), ('problem', 'Проблемный'), ('new', 'Новый')], default='standard', max_length=20, verbose_name='Категория клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField(verbose_name='Дата открытия кредита')),
                ('planned_close_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата закрытия')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Взятая сумма')),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ежемесячный платёж')),
                ('product_type', models.CharField(choices=[('consumer', 'Потребительский'), ('mortgage', 'Ипотека'), ('car', 'Автокредит'), ('credit_card', 'Кредитная карта'), ('microloan', 'Микрозайм')], default='consumer', max_length=20, verbose_name='Тип кредитного продукта')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('closed', 'Закрыт'), ('overdue', 'Просрочен'), ('default', 'Дефолт'), ('restructured', 'Реструктурирован')], default='active', max_length=20, verbose_name='Статус кредита')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='collection_app.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредиты',
            },
        ),
        migrations.CreateModel(
            name='ScoringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateField(verbose_name='Дата расчёта')),
                ('probability', models.FloatField(verbose_name='Вероятность')),
                ('risk_segment', models.CharField(choices=[('low', 'Низкий риск'), ('medium', 'Средний риск'), ('high', 'Высокий риск'), ('critical', 'Критический риск')], default='medium', max_length=20, verbose_name='Сегмент риска')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorings', to='collection_app.client', verbose_name='Клиент')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorings', to='collection_app.credit', verbose_name='Кредит')),
            ],
            options={
                'verbose_name': 'Результат прогнозирования',
                'verbose_name_plural': 'Результаты прогнозирования',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма платежа')),
                ('payment_type', models.CharField(choices=[('regular', 'Регулярный'), ('early', 'Досрочный'), ('partial', 'Частичный'), ('penalty', 'Штраф')], default='regular', max_length=20, verbose_name='Тип платежа')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата платежа')),
                ('min_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Минимальный платёж')),
                ('overdue_days', models.IntegerField(default=0, verbose_name='Просрочка по платежу (дней)')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='collection_app.credit', verbose_name='Кредит')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО оператора')),
                ('role', models.CharField(default='operator', max_length=100, verbose_name='Роль / группа')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата трудоустройства')),
                ('current_load', models.IntegerField(default=0, verbose_name='Текущая нагрузка')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('break', 'Перерыв'), ('offline', 'Не в сети'), ('on_call', 'На звонке')], default='active', max_length=20, verbose_name='Статус оператора')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторы',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время воздействия')),
                ('intervention_type', models.CharField(choices=[('phone', 'Звонок'), ('sms', 'СМС'), ('email', 'Email'), ('letter', 'Письмо'), ('visit', 'Визит')], default='phone', max_length=20, verbose_name='Тип воздействия')),
                ('status', models.CharField(choices=[('completed', 'Завершено'), ('no_answer', 'Не дозвон'), ('promise', 'Обещание'), ('refuse', 'Отказ'), ('callback', 'Перезвонить')], default='completed', max_length=20, verbose_name='Статус воздействия')),
                ('duration', models.IntegerField(default=0, verbose_name='Длительность разговора (сек)')),
                ('promise_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма обещания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='collection_app.client', verbose_name='Клиент')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='collection_app.credit', verbose_name='Кредит')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection_app.operator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Воздействие',
                'verbose_name_plural': 'Воздействия',
            },
        ),
        migrations.CreateModel(
            name='CreditState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_date', models.DateField(verbose_name='Дата состояния')),
                ('principal_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Основной долг')),
                ('overdue_principal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Просроченный основной долг')),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Проценты')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='collection_app.credit', verbose_name='Кредит')),
            ],
            options={
                'verbose_name': 'Состояние кредита',
                'verbose_name_plural': 'Состояния кредитов',
            },
        ),
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('approved_probability', models.FloatField(blank=True, null=True, verbose_name='Вероятность одобрения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection_app.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка на кредит',
                'verbose_name_plural': 'Заявки на кредиты',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_name', models.CharField(max_length=300, verbose_name='ФИО должника')),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма просрочки')),
                ('overdue_days', models.IntegerField(default=0, verbose_name='Срок просрочки (дней)')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет воздействия')),
                ('assignment_date', models.DateField(verbose_name='Дата')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection_app.credit', verbose_name='Кредит')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection_app.operator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Распределение работы',
                'verbose_name_plural': 'Распределения работы',
            },
        ),
    ]
