# Generated by Django 6.0.1 on 2026-01-20 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0002_smartscript_clientbehaviorprofile_compliancealert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='has_children',
        ),
        migrations.AddField(
            model_name='assignment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection_app.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='client',
            name='children_count',
            field=models.IntegerField(default=0, verbose_name='Количество детей'),
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='client',
            name='employer_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='credit',
            name='actuality_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата актуальности'),
        ),
        migrations.AddField(
            model_name='credit',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процентная ставка'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='decision',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отказано')], default='pending', max_length=20, verbose_name='Решение'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='decision_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата решения'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='overdue_risk_probability',
            field=models.FloatField(blank=True, null=True, verbose_name='Риск просрочки'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='requested_term',
            field=models.IntegerField(default=12, verbose_name='Срок кредита (месяцев)'),
        ),
        migrations.AddField(
            model_name='creditstate',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_states', to='collection_app.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='creditstate',
            name='overdue_close_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закрытия просрочки'),
        ),
        migrations.AddField(
            model_name='creditstate',
            name='overdue_days',
            field=models.IntegerField(default=0, verbose_name='Длительность просрочки (дней)'),
        ),
        migrations.AddField(
            model_name='creditstate',
            name='overdue_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Просроченные проценты'),
        ),
        migrations.AddField(
            model_name='creditstate',
            name='overdue_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала просрочки'),
        ),
        migrations.AddField(
            model_name='creditstate',
            name='penalties',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Штрафы'),
        ),
        migrations.AddField(
            model_name='creditstate',
            name='planned_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Плановая дата платежа'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='promise_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обещания'),
        ),
        migrations.AddField(
            model_name='payment',
            name='actuality_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата актуальности'),
        ),
        migrations.AddField(
            model_name='scoringresult',
            name='predicted_overdue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Прогнозируемая дата просрочки'),
        ),
        migrations.CreateModel(
            name='OperatorStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('calls_count', models.IntegerField(default=0, verbose_name='Количество звонков')),
                ('successful_contacts', models.IntegerField(default=0, verbose_name='Успешные контакты')),
                ('promises_received', models.IntegerField(default=0, verbose_name='Количество обещаний')),
                ('total_collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма погашенной задолженности')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='collection_app.operator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Статистика оператора',
                'verbose_name_plural': 'Статистика операторов',
                'ordering': ['-period_start'],
            },
        ),
    ]
