# Generated by Django automation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0004_callscript_collectioncase_legalcase_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий оператора'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='refusal_reason',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Причина отказа'),
        ),
    ]
