# Generated by Django 6.0.1 on 2026-03-03 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0005_intervention_notes_refusal_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankruptcyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата проверки')),
                ('is_bankrupt', models.BooleanField(default=False, verbose_name='Признан банкротом')),
                ('bankruptcy_case_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Номер дела')),
                ('bankruptcy_date', models.DateField(blank=True, null=True, verbose_name='Дата признания')),
                ('source', models.CharField(default='ЕФРСБ', max_length=100, verbose_name='Источник данных')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали проверки')),
            ],
            options={
                'verbose_name': 'Проверка банкротства',
                'verbose_name_plural': 'Проверки банкротства',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='MLModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модели')),
                ('version', models.CharField(max_length=50, verbose_name='Версия')),
                ('model_type', models.CharField(max_length=50, verbose_name='Тип алгоритма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обучения')),
                ('accuracy', models.FloatField(default=0, verbose_name='Accuracy')),
                ('precision', models.FloatField(default=0, verbose_name='Precision')),
                ('recall', models.FloatField(default=0, verbose_name='Recall')),
                ('f1_score', models.FloatField(default=0, verbose_name='F1-Score')),
                ('roc_auc', models.FloatField(default=0, verbose_name='ROC-AUC')),
                ('cv_mean', models.FloatField(default=0, verbose_name='CV Mean')),
                ('cv_std', models.FloatField(default=0, verbose_name='CV Std')),
                ('hyperparameters', models.JSONField(default=dict, verbose_name='Гиперпараметры')),
                ('feature_names', models.JSONField(default=list, verbose_name='Признаки')),
                ('feature_importances', models.JSONField(default=dict, verbose_name='Важность признаков')),
                ('confusion_matrix', models.JSONField(default=list, verbose_name='Матрица ошибок')),
                ('roc_curve_fpr', models.JSONField(default=list, verbose_name='ROC FPR')),
                ('roc_curve_tpr', models.JSONField(default=list, verbose_name='ROC TPR')),
                ('training_data_size', models.IntegerField(default=0, verbose_name='Размер обучающей выборки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная модель')),
                ('model_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Путь к файлу модели')),
            ],
            options={
                'verbose_name': 'Версия ML-модели',
                'verbose_name_plural': 'Версии ML-моделей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='collection__user_id_14c297_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='collection__model_n_8a8614_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='collection__action_e358fa_idx',
        ),
        migrations.AddField(
            model_name='assignment',
            name='ab_group',
            field=models.CharField(choices=[('A', 'Контрольная (обычное)'), ('B', 'Экспериментальная (умное)')], default='B', max_length=2, verbose_name='A/B группа'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_method',
            field=models.CharField(default='smart', max_length=30, verbose_name='Метод назначения'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='match_score',
            field=models.FloatField(default=0, verbose_name='Качество матчинга'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection_app.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(default=dict, verbose_name='Детали'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection_app.operator', verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('critical', 'Критическое')], default='info', max_length=10, verbose_name='Серьёзность'),
        ),
        migrations.AddField(
            model_name='client',
            name='bankruptcy_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата признания банкротом'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_refused',
            field=models.BooleanField(default=False, verbose_name='Отказ от взаимодействия (230-ФЗ ст.8)'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_refused_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отказа'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_bankrupt',
            field=models.BooleanField(default=False, verbose_name='Признан банкротом'),
        ),
        migrations.AddField(
            model_name='scoringresult',
            name='cost_per_contact',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=8, verbose_name='Стоимость контакта (₽)'),
        ),
        migrations.AddField(
            model_name='scoringresult',
            name='expected_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ожидаемая прибыль (₽)'),
        ),
        migrations.AddField(
            model_name='scoringresult',
            name='expected_recovery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ожидаемый возврат (₽)'),
        ),
        migrations.AddField(
            model_name='scoringresult',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Грейд (A-E)'),
        ),
        migrations.AddField(
            model_name='scoringresult',
            name='model_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип алгоритма'),
        ),
        migrations.AddField(
            model_name='scoringresult',
            name='model_version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Версия модели'),
        ),
        migrations.AddField(
            model_name='scoringresult',
            name='roc_auc',
            field=models.FloatField(blank=True, null=True, verbose_name='ROC-AUC модели'),
        ),
        migrations.AddField(
            model_name='scoringresult',
            name='score_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скоринговый балл (300-850)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('intervention_create', 'Создание воздействия'), ('intervention_update', 'Обновление воздействия'), ('assignment_create', 'Назначение клиента'), ('assignment_delete', 'Удаление назначения'), ('scoring_run', 'Запуск скоринга'), ('model_train', 'Обучение модели'), ('distribution_run', 'Распределение клиентов'), ('compliance_violation', 'Нарушение комплаенса'), ('bankruptcy_check', 'Проверка банкротства'), ('contact_blocked', 'Контакт заблокирован'), ('login', 'Вход в систему'), ('logout', 'Выход из системы')], db_index=True, max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['operator', 'assignment_date'], name='idx_assign_op_date'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['credit'], name='idx_assign_credit'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['ab_group'], name='idx_assign_ab'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='idx_audit_action_ts'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['operator', '-timestamp'], name='idx_audit_op_ts'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['full_name'], name='idx_client_fullname'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone_mobile'], name='idx_client_phone'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_bankrupt'], name='idx_client_bankrupt'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['contact_refused'], name='idx_client_refused'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['client', '-datetime'], name='idx_interv_client_dt'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['operator', '-datetime'], name='idx_interv_op_dt'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['status'], name='idx_interv_status'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['credit'], name='idx_interv_credit'),
        ),
        migrations.AddIndex(
            model_name='scoringresult',
            index=models.Index(fields=['client', '-calculation_date'], name='idx_scoring_client_date'),
        ),
        migrations.AddIndex(
            model_name='scoringresult',
            index=models.Index(fields=['score_value'], name='idx_scoring_score'),
        ),
        migrations.AddIndex(
            model_name='scoringresult',
            index=models.Index(fields=['risk_segment'], name='idx_scoring_segment'),
        ),
        migrations.AddIndex(
            model_name='scoringresult',
            index=models.Index(fields=['model_version'], name='idx_scoring_version'),
        ),
        migrations.AddField(
            model_name='bankruptcycheck',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankruptcy_checks', to='collection_app.client', verbose_name='Клиент'),
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='changes',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_repr',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='personal_data_accessed',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user_agent',
        ),
    ]
