# Generated by Django 6.0.1 on 2026-03-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0006_scoring_compliance_bankruptcy_audit_ab'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='refused_channels',
            field=models.JSONField(blank=True, default=list, help_text='JSON-список каналов, от которых клиент отказался (пустой = полный отказ). Пример: ["phone","sms"]', verbose_name='Каналы отказа'),
        ),
        migrations.AddField(
            model_name='client',
            name='third_party_consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на контакт с третьими лицами'),
        ),
        migrations.AddField(
            model_name='client',
            name='third_party_consent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата согласия'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='approved_script_used',
            field=models.BooleanField(default=True, verbose_name='Использован утверждённый скрипт (ст.5)'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='caller_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Исходящий номер (ст.9 — запрет скрытых)'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='is_third_party',
            field=models.BooleanField(default=False, verbose_name='Контакт с третьим лицом'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='operator_identified',
            field=models.BooleanField(default=True, verbose_name='Оператор представился (ст.6)'),
        ),
    ]
