# Generated by Django 6.0.1 on 2026-03-10 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0007_compliance_230fz_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('st1_time', 'Ст.1 Нарушение времени контакта'), ('st2_frequency', 'Ст.2 Превышение частоты контактов'), ('st3_refusal', 'Ст.3 Контакт при отказе клиента'), ('st4_third_party', 'Ст.4 Контакт с третьими лицами без согласия'), ('st5_script', 'Ст.5 Неутверждённый скрипт'), ('st6_identification', 'Ст.6 Нарушение идентификации оператора'), ('st7_bankruptcy', 'Ст.7 Контакт с банкротом'), ('st8_hidden_number', 'Ст.8 Скрытый номер звонящего'), ('st9_interval', 'Ст.9 Нарушение минимального интервала'), ('st10_history', 'Ст.10 Нарушение хранения истории'), ('st11_personal_data', 'Ст.11 Нарушение 152-ФЗ ПДн'), ('other', 'Иное')], max_length=30, verbose_name='Тип нарушения')),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], default='medium', max_length=10, verbose_name='Серьёзность')),
                ('description', models.TextField(verbose_name='Описание нарушения')),
                ('action_blocked', models.BooleanField(default=True, verbose_name='Действие заблокировано')),
                ('contact_type', models.CharField(blank=True, max_length=20, verbose_name='Канал контакта')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Подробности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата нарушения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='collection_app.client', verbose_name='Клиент')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='collection_app.operator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Нарушение 230-ФЗ',
                'verbose_name_plural': 'Нарушения 230-ФЗ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='idx_violation_client_dt'), models.Index(fields=['operator', '-created_at'], name='idx_violation_op_dt'), models.Index(fields=['rule_type'], name='idx_violation_rule'), models.Index(fields=['severity'], name='idx_violation_severity')],
            },
        ),
    ]
