# Generated by Django 4.2.27 on 2026-04-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0008_violationlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['operator', '-assignment_date', 'priority'], name='idx_assign_op_active'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['client', 'status'], name='idx_credit_client_status'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['status', '-open_date'], name='idx_credit_status_open'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['status', 'planned_close_date'], name='idx_credit_status_pclose'),
        ),
        migrations.AddIndex(
            model_name='creditstate',
            index=models.Index(fields=['credit', '-state_date'], name='idx_cstate_credit_date'),
        ),
        migrations.AddIndex(
            model_name='creditstate',
            index=models.Index(fields=['credit', 'planned_payment_date'], name='idx_cstate_credit_pdate'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['intervention_type', 'status', '-datetime'], name='idx_interv_type_status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['credit', '-payment_date'], name='idx_payment_credit_date'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['credit', 'planned_date'], name='idx_payment_credit_planned'),
        ),
    ]
